### ISSUE TITLE
TypeProvider not working in Visual Studio

### ISSUE THREAD

**Issue by JordanMarr** [easybuild-org/EasyBuild.FileSystemProvider#2]
Hi Maxime,

Using the v0.1.1 in a build project and the sample code, I got an error:

![image](https://github.com/easybuild-org/EasyBuild.FileSystemProvider/assets/1030435/81cf3ef7-f97f-405c-a71c-0b8f22e9c4e8)
![image](https://github.com/easybuild-org/EasyBuild.FileSystemProvider/assets/1030435/1d559cd4-f3b2-4bb9-9f8d-e8ceb7447b1b)

My system:
* Windows 11
* Visual Studio Professional 2022
* Tried on both net6.0 and a net8.0 projects with the same results

**Comment by MangelMaxime** [comment]
Hello @JordanMarr,

Could you please have a look into the reported directory and confirm that the `.dll` file is indeed missing?

**Comment by MangelMaxime** [comment]
I was thinking that perhaps it was a Windows issues but I gave it a try on a Windows ARM VM and it seems to be working fine for me.

I tested using VSCode, and I am waiting for VS Studio to install to check with that IDE too.

**Comment by MangelMaxime** [comment]
I am able to reproduce the problem when using VS Community.

However, the TP works fine when using `dotnet cli` or `VSCode`.
